### PR TITLE
refactor cost functions

### PR DESCRIPTION
**Pull request by jd-lara**
This addresses long-standing issues on the cost functions. It also implements the new cost function for the joint energy - services market bid. 

It also removes some hacks to handle PWL functions cases. 

x-ref #514 

cc. @andrewrosemberg @raphaelsaavedra this is WIP for feedback. At this stage the tests don't pass but you can see the path I am taking. 

@claytonpbarrows please take a look.

### CODE REVIEW

**Comment by jd-lara** [comment]
The device's cost functions are ready. The PWL cost function for the ORDC reserve still needs fixing.

**Comment by andrewrosemberg** [comment]
great work José!
I'm looking into your changes and I have a couple of questions:

1. Couldn't find if there is a restriction on negative prices. Is this the case? because renewables and some other subsidized generators (or ones that just really want to be dispatched) sometimes submit **negative prices** and we want to make sure we can cover those.

2. A. Does this cover also **negative MW** ? Some generators might be paid to consume energy so their cost curves might have negative parts (see the weird hydro [here](https://nrel-siip.slack.com/files/U018T00UX45/F01A913JWDQ/special_generators.pdf))  
2. B. On that matter, do you see any problems in allowing generators to have negative `Pmin`? or should we create a new type?

**Comment by raphaelsaavedra** [comment]
>Couldn't find if there is a restriction on negative prices. Is this the case? because renewables and some other subsidized generators (or ones that just really want to be dispatched) sometimes submit negative prices and we want to make sure we can cover those.

Note that PSY and PSI model the cost curve, not the offer curve. While these generators do submit offer curves, the resulting cost curve will always be non-negative.

**Comment by andrewrosemberg** [comment]
> > Couldn't find if there is a restriction on negative prices. Is this the case? because renewables and some other subsidized generators (or ones that just really want to be dispatched) sometimes submit negative prices and we want to make sure we can cover those.
> 
> Note that PSI models the cost curve, not the offer curve. While these generators do submit offer curves, the resulting cost curve will always be non-negative.

Could you give us an example?

**Comment by raphaelsaavedra** [comment]
>Note that PSI models the cost curve, not the offer curve. While these generators do submit offer curves, the resulting cost curve will always be non-negative.

Sorry, I misspoke here. The cost curve can be negative in some points.

>Could you give us an example?

Just consider any offer curve that is a stepwise function starting from negative values. When you integrate that offer curve to get to the cost curve, the result will be a piecewise linear function where the first segment has negative slope (and eventually can have positive slope).

**Comment by andrewrosemberg** [comment]
understood, so in fact, it can be negative. Either @raphaelsaavedra it would be better for you to describe here what are you trying to implement instead of internally.

**Comment by raphaelsaavedra** [comment]
Hi @jd-lara, here's a brief summary of some "edge cases" for generators that we'd like to make sure that PowerSimulations is able to handle.

* Units that submit negative offer prices: from what we've seen, these are usually renewables, but there are some other cases too. Basically units that don't mind being price takers. As mentioned above, this gets translated to a cost curve that can have negative values (but is still convex).
* Units that inform a negative Pmin: these are the so-called DRR type II units, that submit offers together with generators but are basically loads that can reduce their load for a price. This gets translated to an offer curve that is entirely for negative MW values (i.e., Pmin < Pmax < 0). Additionally, there are some rare cases where Pmin < 0 < Pmax (we're not exactly sure what these are, we suspect asynchronous resources).

**Comment by andrewrosemberg** [comment]
Hey, there is another cost to address that might be very easy given the new structure. We need a service-specific pice-wise linear cost. 
Currently, service slacks are unique. Could we perhaps pass them optionally in the problem definition? Remembering that we need piecewise instead of a single slope.

**Comment by jd-lara** [comment]
> Hey, there is another "cost" (actually penalty) that might be very easy to implement given the new structure. We need a service-specific pice-wise-linear slack penalty. 
> Currently, service slacks penalties are a single unique linear value for all services ([ref](https://github.com/NREL-SIIP/PowerSimulations.jl/blob/16e1b453ed21e714db58065e03601af4405b2e54/src/core/definitions.jl#L48)). Could we perhaps pass slack pwl penalties optionally in the problem definition? Remembering that we need piecewise instead of a single slope.

This is already implemented for a slightly different reserve that has a PWL penalty for shortage. Currently that's the one with some issues due to time Variant costs.

**Pull request merged**
