### PR TITLE
Fixing bug in creating initial conditions for Energy variables

### PR DESCRIPTION
**Pull request by sourabhdalvi**
The code would always use system data for any type of energy variables, now its use initial condition data if available.
This will be useful for enabling simulations with model re-build feature

### CODE REVIEW

**Review by jd-lara — APPROVED** [review]

**Review by jd-lara — COMMENTED** [review]
@sourabhdalvi this is a fix for the rebuild but not a systematic one. The code path you are changing here is the build one not the update one.

**Comment by claytonpbarrows** [comment]
#886

**Comment by jd-lara** [comment]
@sourabhdalvi I think that your branch is fixing a slightly different problem which is the fact that this field should be initialized from the initial conditions data if it is available. But during the simulation the initial conditions are always updated from the store so this code path never gets called. So, unless you get a formulation that solves for the initial energy this code path will always use the default data source.

**Comment by jd-lara** [comment]
After reviewing the effects of this PR, it was reversed in 3af8e2c48b733d97b758ac21b3f8133bea1fa346 since it ignores the initial condition in the data.

**Pull request merged**
